_commit: v2
_src_path: gh:kitware-resonant/resonant-meta-template
django_project: false
max_python_minor_version: 14
min_python_minor_version: 12
project_slug: django-resonant-utils
python_package_name: resonant_utils
